/**
 * Demo data for testing the berth schedule component
 */

import type {
  BerthScheduleConfig,
  Berth,
  Bollard,
  VesselCall,
  NonWorkingCall,
  ScheduleItem,
} from './components/types';

export const demoConfiguration: BerthScheduleConfig = {
  backgroundColor: '#ffffff',
  zoom: 1,
  timeLine: {
    startDate: new Date('2024-12-08 00:00'),
    endDate: new Date('2024-12-15 00:00'),
    emPerHour: 2,
    dateFormat: 'DayMonth',
    dateLocale: 'en-US',
    backgroundColor: '#fefefe',
    foregroundColor: '#555599',
    borderColor: '#e0e0e0',
    borderThickness: 1,
    timeGridColor: '#e0e0e0',
    startOfDay: {
      backgroundColor: '#6699aa',
      foregroundColor: '#ffffff',
    },
    hour: {
      backgroundColor: '#66aacc',
      foregroundColor: '#ffffff',
    },
  },
  quay: {
    emPerMeter: 0.7,
    bollardGridColor: '#d0d0d0',
    berthEndColor: '#ff6666',
    showTitle: true,
    showDistance: false,
    backgroundColor: '#f7f7f7',
    foregroundColor: '#555599',
    borderColor: '#e0e0e0',
    borderThickness: 1,
    berths: [
      {
        id: 'berth-01',
        name: 'Berth 01',
        length: 100,
        foregroundColor: '#555599',
        backgroundColor: '#f7f7f7',
        borderColor: '#e0e0e0',
        borderThickness: 1,
        connected: true,
        bollards: [
          {
            id: 'b11',
            name: 'B11',
            distance: 15,
            backgroundColor: '#ee66aa',
            borderColor: '#aaaaaa',
            borderThickness: 1,
          } as Bollard,
          {
            id: 'b12',
            name: 'B12',
            distance: 30,
            backgroundColor: '#6666aa',
            borderColor: '#aaaaaa',
            borderThickness: 1,
          } as Bollard,
          {
            id: 'b13',
            name: 'B13',
            distance: 50,
            backgroundColor: '#6666aa',
            borderColor: '#aaaaaa',
            borderThickness: 1,
          } as Bollard,
          {
            id: 'b14',
            name: 'B14',
            distance: 70,
            backgroundColor: '#6666aa',
            borderColor: '#aaaaaa',
            borderThickness: 1,
          } as Bollard,
          {
            id: 'b15',
            name: 'B15',
            distance: 90,
            backgroundColor: '#6666aa',
            borderColor: '#aaaaaa',
            borderThickness: 1,
          } as Bollard,
        ],
      } as Berth,
      {
        id: 'berth-02',
        name: 'Berth 02',
        length: 120,
        foregroundColor: '#555599',
        backgroundColor: '#f7f7f7',
        borderColor: '#e0e0e0',
        borderThickness: 1,
        connected: true,
        bollards: [
          {
            id: 'b21',
            name: 'B21',
            distance: 20,
            backgroundColor: '#6666aa',
            borderColor: '#aaaaaa',
            borderThickness: 1,
          } as Bollard,
          {
            id: 'b22',
            name: 'B22',
            distance: 40,
            backgroundColor: '#6666aa',
            borderColor: '#aaaaaa',
            borderThickness: 1,
          } as Bollard,
          {
            id: 'b23',
            name: 'B23',
            distance: 60,
            backgroundColor: '#6666aa',
            borderColor: '#aaaaaa',
            borderThickness: 1,
          } as Bollard,
          {
            id: 'b24',
            name: 'B24',
            distance: 80,
            backgroundColor: '#6666aa',
            borderColor: '#aaaaaa',
            borderThickness: 1,
          } as Bollard,
          {
            id: 'b25',
            name: 'B25',
            distance: 100,
            backgroundColor: '#6666aa',
            borderColor: '#aaaaaa',
            borderThickness: 1,
          } as Bollard,
        ],
      } as Berth,
      {
        id: 'berth-03',
        name: 'Berth 03',
        length: 80,
        foregroundColor: '#555599',
        backgroundColor: '#f7f7f7',
        borderColor: '#e0e0e0',
        borderThickness: 1,
        connected: false,
        bollards: [
          {
            id: 'b31',
            name: 'B31',
            distance: 15,
            backgroundColor: '#6666aa',
            borderColor: '#aaaaaa',
            borderThickness: 1,
          } as Bollard,
          {
            id: 'b32',
            name: 'B32',
            distance: 30,
            backgroundColor: '#6666aa',
            borderColor: '#aaaaaa',
            borderThickness: 1,
          } as Bollard,
          {
            id: 'b33',
            name: 'B33',
            distance: 50,
            backgroundColor: '#6666aa',
            borderColor: '#aaaaaa',
            borderThickness: 1,
          } as Bollard,
          {
            id: 'b34',
            name: 'B34',
            distance: 65,
            backgroundColor: '#6666aa',
            borderColor: '#aaaaaa',
            borderThickness: 1,
          } as Bollard,
        ],
      } as Berth,
    ],
  },
  cornerBox: {
    backgroundColor: '#f7f7f7',
    foregroundColor: '#555599',
    borderColor: '#aaaaaa',
    borderThickness: 1,
  },
};

export const demoSchedules: ScheduleItem[] = [
  {
    id: 'call-001',
    name: 'MV OCEAN STAR',
    backgroundColor: '#aaaaff',
    foregroundColor: '#333366',
    textForegroundColor: '#ffffff',
    textBackgroundColor: '#6688dd',
    borderColor: '#8899aa',
    borderThickness: 2,
    description: 'Container Vessel',
    startBollardId: 'b12',
    endBollardId: 'b14',
    startDate: new Date('2024-12-09 08:00'),
    endDate: new Date('2024-12-10 18:00'),
    zIndex: 5,
    vessel: {
      id: 'vessel-001',
      name: 'MV OCEAN STAR',
      LOA: 45,
      draft: 12.5,
      nationality: 'nl',
      vesselType: 'ContainerShip',
      foregroundColor: '#ffffff',
    },
    voyage: {
      voyageNoIn: 'V001-IN',
      voyageNoOut: 'V001-OUT',
      side: 'Port',
      shippingLine: 'MAERSK',
      operations: '1500 TEU',
      timing: {
        anchorage: new Date('2024-12-09 06:00'),
        berth: new Date('2024-12-09 08:00'),
        startOperation: new Date('2024-12-09 09:30'),
        endOperation: new Date('2024-12-10 16:00'),
        unberth: new Date('2024-12-10 17:30'),
        fullaway: new Date('2024-12-10 18:00'),
      },
    },
    margin: {
      left: 2,
      right: 1,
    },
  } as VesselCall,
  {
    id: 'call-002',
    name: 'MV PACIFIC TRADER',
    backgroundColor: '#66dd66',
    foregroundColor: '#333366',
    textForegroundColor: '#ffffff',
    textBackgroundColor: '#33aa44',
    borderColor: '#99aadd',
    borderThickness: 2,
    description: 'General Cargo - LOCKED POSITION',
    startBollardId: 'b21',
    endBollardId: 'b23',
    startDate: new Date('2024-12-09 14:00'),
    endDate: new Date('2024-12-11 10:00'),
    zIndex: 5,
    moveLocked: true,
    vessel: {
      id: 'vessel-002',
      name: 'MV PACIFIC TRADER',
      LOA: 60,
      draft: 10.0,
      nationality: 'de',
      vesselType: 'GeneralCargo',
      foregroundColor: '#ffffff',
    },
    voyage: {
      voyageNoIn: 'V002-IN',
      voyageNoOut: 'V002-OUT',
      side: 'Starboard',
      shippingLine: 'MSC',
      operations: '8000 tons',
    },
  } as VesselCall,
  {
    id: 'call-003',
    name: 'MV ATLANTIC BULK',
    backgroundColor: '#ffaaaa',
    foregroundColor: '#333366',
    textForegroundColor: '#ffffff',
    textBackgroundColor: '#dd6666',
    borderColor: '#555555',
    borderThickness: 2,
    description: 'Bulk Carrier',
    startBollardId: 'b14',
    endBollardId: 'b22',
    startDate: new Date('2024-12-11 06:00'),
    endDate: new Date('2024-12-12 20:00'),
    zIndex: 5,
    hasError: true,
    vessel: {
      id: 'vessel-003',
      name: 'MV ATLANTIC BULK',
      LOA: 85,
      draft: 14.0,
      nationality: 'gb',
      vesselType: 'BulkCargo',
      foregroundColor: '#ffffff',
    },
    voyage: {
      voyageNoIn: 'V003-IN',
      voyageNoOut: 'V003-OUT',
      side: 'Port',
      operations: '25000 tons coal',
      timing: {
        berth: new Date('2024-12-11 06:00'),
        startOperation: new Date('2024-12-11 08:00'),
        endOperation: new Date('2024-12-12 18:00'),
        fullaway: new Date('2024-12-12 20:00'),
      },
    },
    margin: {
      left: 3,
      right: 2,
    },
  } as VesselCall,
  {
    id: 'call-004',
    name: 'MV NORDIC TANKER',
    backgroundColor: '#ffdd66',
    foregroundColor: '#333366',
    textForegroundColor: '#ffffff',
    textBackgroundColor: '#dd9933',
    borderColor: '#555555',
    borderThickness: 2,
    description: 'Oil Tanker - LOCKED OPERATION TIME',
    startBollardId: 'b24',
    endBollardId: 'b32',
    startDate: new Date('2024-12-10 12:00'),
    endDate: new Date('2024-12-11 22:00'),
    zIndex: 5,
    operationTimeLocked: true,
    vessel: {
      id: 'vessel-004',
      name: 'MV NORDIC TANKER',
      LOA: 75,
      draft: 13.5,
      nationality: 'no',
      vesselType: 'OilTanker',
      foregroundColor: '#333333',
    },
    voyage: {
      voyageNoIn: 'V004-IN',
      voyageNoOut: 'V004-OUT',
      side: 'Starboard',
      shippingLine: 'NORDIC OIL',
      operations: '15000 m³',
      timing: {
        anchorage: new Date('2024-12-10 10:00'),
        berth: new Date('2024-12-10 12:00'),
        startOperation: new Date('2024-12-10 13:00'),
        endOperation: new Date('2024-12-11 20:00'),
        unberth: new Date('2024-12-11 21:30'),
        fullaway: new Date('2024-12-11 22:00'),
      },
    },
  } as VesselCall,
  {
    id: 'maintenance-001',
    name: 'Crane Maintenance',
    backgroundColor: '#99ff99',
    foregroundColor: '#333366',
    borderColor: '#555555',
    borderThickness: 1,
    borderStyle: 'dashed',
    description: 'Scheduled Maintenance',
    startBollardId: 'b31',
    endBollardId: 'b33',
    startDate: new Date('2024-12-09 00:00'),
    endDate: new Date('2024-12-09 12:00'),
    reason: 'Maintenance',
    zIndex: 1,
    hideStartTime: true,
    hideEndTime: true,
    hideBollards: true,
    image: '/assets/maintenance.png',
  } as NonWorkingCall,
  {
    id: 'reserved-001',
    name: 'Reserved for VIP Vessel',
    backgroundColor: '#ff6666',
    foregroundColor: '#ffffff',
    borderColor: '#aa0000',
    borderThickness: 1,
    borderStyle: 'dotted',
    description: 'Reserved Area',
    startBollardId: 'b11',
    endBollardId: 'b12',
    startDate: new Date('2024-12-12 00:00'),
    endDate: new Date('2024-12-14 00:00'),
    reason: 'PortPlan',
    zIndex: 0,
    hideStartTime: true,
    hideEndTime: true,
  } as NonWorkingCall,
  {
    id: 'call-005',
    name: 'MV GAS PRINCESS',
    backgroundColor: '#dd99ff',
    foregroundColor: '#333366',
    textForegroundColor: '#ffffff',
    textBackgroundColor: '#9966cc',
    borderColor: '#885599',
    borderThickness: 2,
    description: 'LNG Tanker',
    startBollardId: 'b11',
    endBollardId: 'b13',
    startDate: new Date('2024-12-12 14:00'),
    endDate: new Date('2024-12-13 08:00'),
    zIndex: 5,
    vessel: {
      id: 'vessel-005',
      name: 'MV GAS PRINCESS',
      LOA: 50,
      draft: 11.0,
      nationality: 'jp',
      vesselType: 'GasTanker',
      foregroundColor: '#ffffff',
    },
    voyage: {
      voyageNoIn: 'V005-IN',
      voyageNoOut: 'V005-OUT',
      side: 'Starboard',
      shippingLine: 'JERA',
      operations: '8000 m³ LNG',
    },
    margin: {
      left: 1,
      right: 1,
    },
  } as VesselCall,
  {
    id: 'call-006',
    name: 'MV CHEM CARRIER',
    backgroundColor: '#66ffcc',
    foregroundColor: '#333366',
    textForegroundColor: '#ffffff',
    textBackgroundColor: '#33bb99',
    borderColor: '#449977',
    borderThickness: 2,
    description: 'Chemical Tanker',
    startBollardId: 'b33',
    endBollardId: 'b34',
    startDate: new Date('2024-12-13 10:00'),
    endDate: new Date('2024-12-14 06:00'),
    zIndex: 5,
    vessel: {
      id: 'vessel-006',
      name: 'MV CHEM CARRIER',
      LOA: 35,
      draft: 9.5,
      nationality: 'se',
      vesselType: 'ChemicalTanker',
      foregroundColor: '#ffffff',
    },
    voyage: {
      voyageNoIn: 'V006-IN',
      voyageNoOut: 'V006-OUT',
      side: 'Port',
      shippingLine: 'STOLT',
      operations: '5000 tons chemicals',
    },
  } as VesselCall,
  {
    id: 'call-007',
    name: 'MV RO-RO EXPRESS',
    backgroundColor: '#ffaa66',
    foregroundColor: '#333366',
    textForegroundColor: '#ffffff',
    textBackgroundColor: '#dd7733',
    borderColor: '#cc6622',
    borderThickness: 2,
    description: 'Ro-Ro Vessel',
    startBollardId: 'b22',
    endBollardId: 'b24',
    startDate: new Date('2024-12-13 18:00'),
    endDate: new Date('2024-12-14 12:00'),
    zIndex: 5,
    vessel: {
      id: 'vessel-007',
      name: 'MV RO-RO EXPRESS',
      LOA: 60,
      draft: 8.0,
      nationality: 'de',
      vesselType: 'Ro-Ro',
      foregroundColor: '#ffffff',
    },
    voyage: {
      voyageNoIn: 'V007-IN',
      voyageNoOut: 'V007-OUT',
      side: 'Starboard',
      shippingLine: 'DFDS',
      operations: '150 vehicles',
      timing: {
        berth: new Date('2024-12-13 18:00'),
        startOperation: new Date('2024-12-13 19:00'),
        endOperation: new Date('2024-12-14 11:00'),
        fullaway: new Date('2024-12-14 12:00'),
      },
    },
  } as VesselCall,
];
